---
title: RafikCMS f
baseURL: "/"
params:
  palette: blue
  header:
    title: RafikCMS
    tagline: CMS karya wong Gresik
    logo_img: "/images/rafikcms 1st.png"
    bg_img: "/images/photo_2019-09-21_11-42-57.jpg"
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved. 2020."
    links:
    - text: Made with RAFIKCMS
      url: https://cepatbuat.website
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
